### ISSUE TITLE
Maven central?

### ISSUE THREAD

**Issue by FranklinChen** [federkasten/appbundle-maven-plugin#14]
I noticed http://mvnrepository.com/artifact/sh.tak.appbundler/appbundle-maven-plugin does not have the latest version of the plugin?

**Comment by federkasten** [comment]
Oh. It's my mistake. Thanks for reporting.

I'll fix soon.

**Comment by federkasten** [comment]
Deployed. <https://oss.sonatype.org/content/repositories/releases/sh/tak/appbundler/appbundle-maven-plugin/1.0.2/> 

It will be indexed into maven search soon.
