### ISSUE TITLE
Built applications force discrete GPU usage

### ISSUE THREAD

**Issue by azhemoytuk** [federkasten/appbundle-maven-plugin#25]
<key>NSSupportsAutomaticGraphicsSwitching</key>
    <true/>

needs to be added to plist template.

Refer as well to:
https://bugs.openjdk.java.net/browse/JDK-8041900
https://bugs.openjdk.java.net/browse/JDK-8132759
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8041900
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8132759

Starting with java 8u76 the plist option will have proper effect (verified on 8u76 beta 4).

**Comment by federkasten** [comment]
Fixed in #26. Thanks.
