### ISSUE TITLE
Some issues with iconFile, fails with multi module maven projects

### ISSUE THREAD

**Issue by nresare** [federkasten/appbundle-maven-plugin#30]
There are a couple of issues with iconFile:

1. It looks for the path in target/classes relative to the current working directory, which breaks
   when you have a multi module project such as https://github.com/nresare/javapasswordsafe
2. When iconFile lookup fails it fails silently, with no indication that anything went wrong
3. The file is expected to be located resources, that gets copied to target/classes which gets
   included in any jars built, resulting in two copies of the icon in the .app. If 
   appbundle-maven-plugin were to look for the directly in the project directory you could exclude
   it from the jar. (As a datapoint, AppIcon.icns for i.e. Numbers.app is 331KiB)

**Comment by federkasten** [comment]
I have released version `1.1.1`. 

I will fix the problems 1 and 2.

**Comment by nresare** [comment]
Thank you, @federkasten
