### ISSUE TITLE
How to package resources in to "Contents/Resources"?

### ISSUE THREAD

**Issue by hepiyellow** [federkasten/appbundle-maven-plugin#36]
My packaged application on OS X has the "Contents" folder, and in it:
- Java
- MacOS
- Plugins
- Resources

I figured that "Resources" would be a good place to put my resources instead of packing them inside a JAR.

Does this plugin help in doing that?

**Comment by federkasten** [comment]
No.

`additionalBundledClasspathResources` option may helps you. It copies resources into `Contents/Java/lib/`.
