### ISSUE TITLE
appbundle-maven-plugin/build.sh: clang: not found

### ISSUE THREAD

**Issue by Sharcoux** [federkasten/appbundle-maven-plugin#37]
I needed to make a few changes in your plugin to adapt to my app, but I couldn't generate the maven plugin and got this error: appbundle-maven-plugin/build.sh: clang: not found.

How am I supposed to generate the plugin ?

Thanks for your help !

**Comment by federkasten** [comment]
You need to install Xcode and Xcode Command Line Tools on mac.

Please see Apple's developer documents for more details.

**Comment by Sharcoux** [comment]
Ok, thank you.

After going deeper into the problem, I installed clang, but the issue is that I don't have Cocoa on Linux. I will try to find someone using a Mac.

By the way, [[ is a bash command. You should consider replacing `#!/bin/sh` by `#!/bin/bash` in build.sh

**Comment by Sharcoux** [comment]
Ok, I can't find anyone with xCode or willing to install it. I'm very sorry to ask you that, but would you mind executing a 'mvn clean deploy' for me if I make you a contributor of my fork ?

My corrections where about the fact that your plugin adds all the dependencies to the package, but my jar already includes them, so the final package is twice heavier ! The second issue is about the fact that I wanted additionalBundledClasspathResources to be placed in the same folder as the jar file.

**Comment by Sharcoux** [comment]
Ok, I found someone on stackoverflow that did it for me. Anyway, if you see any way to make the plugin buildable without xCode, I'm interested.

Thanks a lot for your work !

**Comment by federkasten** [comment]
Sorry for late reply. 

I think it's hard and complicated to cross-compile Mac binaries.
But I'm also interested in building on other platforms, so PR is welcome.

Thanks.
