### ISSUE TITLE
Doesn't build the DMG on macOS 10.12.6

### ISSUE THREAD

**Issue by Sami32** [federkasten/appbundle-maven-plugin#54]
[This warning](https://github.com/federkasten/appbundle-maven-plugin/blob/119432ffb35b4d66be449c89ae1dac35d92cffe0/src/main/java/sh/tak/appbundler/CreateApplicationBundleMojo.java#L486) is displayed while building using Maven 3.3.9.
It build fine under Linux OS.
I suspect that it come from `if (SystemUtils.IS_OS_MAC) {` instead of being:
`if (SystemUtils.IS_OS_MAC_OSX || SystemUtils.IS_OS_MAC) {`

**Comment by mobreza** [comment]
@Sami32 This is fixed in ef35749 and included in the *1.2.1-SNAPSHOT* build.

**Comment by Sami32** [comment]
Cool 👍
The 1.2.1-SNAPSHOT miss the metadata xml file to be downloaded from Maven.

**Comment by federkasten** [comment]
Fixed and deployed in`1.2.1-SNAPSHOT`. Sorry for the inconvenience.
