### ISSUE TITLE
Maven option for including local JRE

### ISSUE THREAD

**Issue by fotisp** [federkasten/appbundle-maven-plugin#8]
Hello,

I went over the documentation here https://java.net/downloads/appbundler/appbundler.html in order to better understand what you do in the mojo code.

Nonetheless, I cannot figure out if I need to copy the jre myself manually into a location (which location?) within the generated .app bundle or if there is an option for it. 

It seems that the option in the ant task is called "runtime", but looking over your code in the mojo I can't find a similar one.

Could you provide some insight on the above?

Thank you,
Fotis

**Comment by federkasten** [comment]
Sorry for replying too late.

This appbundler-plugin has not functions to embed JRE runtime into an application bundle. 

This requires users to install JRE by themselves.

**Comment by chanomie** [comment]
It would be a nice enhancement to include.  The app bundler ant task from Oracle let's you specify the runtime and it will bundle it all in so that it runs, even if people don't have the JRE installed.

Oracle even claims you can package you bundle and put it into the Mac App Store.

```
    <bundleapp outputdirectory="target"
        <runtime dir="${env.JAVA_HOME}" />
    </bundleapp>
```

**Comment by federkasten** [comment]
OK. I will implement this function in the next step.

Needless to say, PR is welcome.

**Comment by jdiligence** [comment]
Yes please. I need to be able to bundle a JRE with my app from now on.

Now that apple isn't installing a JRE for users when required, it is confusing many users because even when the user downloads and installs the Oracle JRE, the system path isn't changed, so the app still doesn't find java!

**Comment by chanomie** [comment]
As a temporary work around, you can use the Oracle bundler ant task to do it.  I've actually got my main build working through Maven using this maven build task.

But to build the app with the JRE bundled into it, I'm still using a very simple build.xml with a single ant task in it.

    
    <bundleapp outputdirectory="target"
        name="${app.name}"
        displayname="${app.name}"
        identifier="${app.mainclass}"
        icon="${app.icons}"
        mainclassname="${app.mainclass}" >

        <runtime dir="${env.JAVA_HOME}" / >
        <classpath dir="target/lib" />
        <option value="-Dapple.laf.useScreenMenuBar=true"/>
        <option value="-Dapple.awt.brushMetalLook=true"/>
    </bundleapp>

**Comment by jdiligence** [comment]
There is an improved fork of appbundler here if you are interested. https://bitbucket.org/infinitekind/appbundler

However, it still has a limitation that I am waiting for a reply about. I need to be able to include a few extra executables and set the working directory so my app can call them. I can't see a way with appbundler. My app needs to call these executables.

I think I may be able to tweak jarbundler to include a JRE instead. jarbundler can already include files that must be executable. I am now seeing if I can fool it into copying a JRE into Plugins in the app bundle.

**Comment by federkasten** [comment]
Thanks for #17 pull request, it become possible to bundle JRE. Check it out.
